# Generated by Django 5.0.4 on 2024-04-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activity",
            table="activity",
        ),
    ]
